#!/usr/bin/perl

#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use esmith::Build::CreateLinks qw(:all);

#
# nethserver-flashstart-hybrid-update event
#

my $event = 'nethserver-flashstart-hybrid-update';

event_actions($event, qw(
      initialize-default-databases 00
));

event_templates($event, qw(
      /etc/cron.d/flashstart-auth-ip
      /etc/cron.d/flashstart-hybrid
));

#
# nethserver-flashstart-hybrid-save event
#

$event = 'nethserver-flashstart-hybrid-save';

event_actions($event, qw(
      flashstarthybrid-init 40
      firewall-adjust 60
      nethserver-flashstart-auth-ip 70
));

event_templates($event, qw(
      /etc/cron.d/flashstart-auth-ip
));

#
# wan-uplink-update event
#

$event = 'wan-uplink-update';

event_actions($event, qw(
      nethserver-flashstart-hybrid-auth-ip 90
));


#
# interface-update event
#

$event = 'interface-update';

event_actions($event, qw(
      flashstarthybrid-send-settings 90
      nethserver-flashstart-hybrid-auth-ip 90
));

# 
# flashstarthybrid-dns-update
#

$event = 'flashstarthybrid-dns-update';

event_actions($event, qw(
      flashstarthybrid-restart-dnsmasq 30
      firewall-adjust 40
));

# 
# flashstarthybrid-zone-update
#

$event = 'flashstarthybrid-zone-update';

event_actions($event, qw(
      flashstarthybrid-restart-dnsmasq 30
      flashstarthybrid-expand-dnsmasq 40
));

#
# firewall-adjust
#

$event = 'firewall-adjust';

event_actions($event, qw(
      flashstarthybrid-object-update 90
));
