#!/bin/sh

#-------------------------------------------------------------
# FLASHSTART HYBRID - init SCRIPTS
#-------------------------------------------------------------
# check init inlcude defined in fs_hybrid
if [ "$INIT_SRC_INCLUDE" != "1" ]; then echo "call %SCRIPT_DIR%/%SCRIPT_FS% init"; exit; fi


# reset ifconfig, ipset and restart firewall rules
$SIGNAL_EVENT flashstarthybrid-dns-init

# if API configured 
if [ "$AUTH_EMAIL" != "" -a "$AUTH_PASS" != "" ]; then
	# call job inizialization
	$SCRIPT_FS init_jobs "0"
fi
