#!/bin/bash

#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

. /usr/libexec/nethserver/api/lib/helper_functions

# read json from stdin
data=$(cat /dev/stdin)

enable_flashstart=$(echo $data | jq -r '.enableFlashstart')
username=$(echo $data | jq -r '.username')
password=$(echo $data | jq -r '.password')
rolesFilter=$(echo $data | jq -r '.rolesFilter | join(",")')
bypass=$(echo $data | jq -r '.bypass | join(",")')

if [ "$enable_flashstart" = "enabled" ]; then
    /sbin/e-smith/config setprop flashstart status "$enable_flashstart" Username "$username" \
        Password "$password" Roles "$rolesFilter" Bypass "$bypass"

    if [ $? -gt 0 ]; then
        invalid_error
    fi
else
    /sbin/e-smith/config setprop flashstart status "$enable_flashstart"

    if [ $? -gt 0 ]; then
        invalid_error
    fi
fi

/sbin/e-smith/signal-event -j nethserver-flashstart-save
if [ $? -gt 0 ]; then
    error "EventFailed" "See /var/log/messages"
else
    success
fi
